/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2025-02-23 18:57:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.benutzer.aussensicht.BenutzerBean;
import java.util.List;
import model.benutzer.aussensicht.BenutzerBean;

public final class benutzeranlegen_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/administration.jsp", Long.valueOf(1740256945182L));
    _jspx_dependants.put("/navigation.jsp", Long.valueOf(1740331482016L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.benutzer.aussensicht.BenutzerBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>NeoFinova</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("    font-family: Arial, sans-serif;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Navbar stil ayarları */\r\n");
      out.write(".navbar {\r\n");
      out.write("    background-color: #00BFFF;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    padding: 0 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar ul {\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Menü öğeleri */\r\n");
      out.write(".navbar ul li {\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Link stilleri */\r\n");
      out.write(".navbar ul li a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    color: white;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 14px 20px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar ul li a:hover {\r\n");
      out.write("    background-color: #575757;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".abmelden {\r\n");
      out.write("    margin-left: auto;\r\n");
      out.write("    display: flex; /* Flexbox düzeni kullan */\r\n");
      out.write("    align-items: center; /* Dikey hizalamayı merkezde tut */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".abmelden a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    color: white;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 14px 20px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    background-color: red;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    margin-left: 10px; /* Kullanıcı bilgisi ile buton arasında boşluk ekle */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".abmelden a:hover {\r\n");
      out.write("    background-color: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-info {\r\n");
      out.write("    margin-left: 1px; /* Boşluk ayarı */\r\n");
      out.write("    align-items: center; /* Dikey hizalama */\r\n");
      out.write("    display: flex; /* Kullanıcı bilgisi için flexbox kullan */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".username {\r\n");
      out.write("    margin-left: 5px; /* İkon ve kullanıcı adı arasında boşluk */\r\n");
      out.write("    color: white; /* Yazının rengi */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"administration.jsp\">Administration</a></li>\r\n");
      out.write("            <li><a href=\"#\">Pfändung</a></li>\r\n");
      out.write("            <li><a href=\"#\">Server</a></li>\r\n");
      out.write("            <li><a href=\"#\">Druck</a></li>\r\n");
      out.write("            <li><a href=\"#\">Testseite</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"abmelden\">\r\n");
      out.write("        ");

        BenutzerBean benutzer =(BenutzerBean) session.getAttribute("benutzerBean");
        if(benutzer != null){
        	
      out.write("\r\n");
      out.write("            <div class=\"user-info\">\r\n");
      out.write("                <i class=\"fas fa-user\"></i> \r\n");
      out.write("                <span class=\"username\">");
      out.print( benutzer.getUsername() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");

        	
        } else {
        	
      out.write("\r\n");
      out.write("            <p style=\"color: red;\">Kullanıcı bulunamadı!</p>\r\n");
      out.write("        ");

            }
        
        
      out.write("\r\n");
      out.write("        <a href=\"abmelden\">Abmelden</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Adminisration</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("    font-family: Arial, sans-serif;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write(".nav-container{\r\n");
      out.write("background-color: #00BFFF;\r\n");
      out.write("    width: 200px; \r\n");
      out.write("    height: 86vh;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: left;\r\n");
      out.write("    padding: 0 10px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".nav-container ul li{\r\n");
      out.write("float left\r\n");
      out.write("}\r\n");
      out.write(".nav-container ul {\r\n");
      out.write("    list-style-type: none; /* Noktaları kaldır */\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write(".nav-container ul li a{\r\n");
      out.write("    display: block;\r\n");
      out.write("    color: white;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 14px 20px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".nav-container ul li a:hover{\r\n");
      out.write(" background-color: #575757;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h1>Administration</h1>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"nav-container\">\r\n");
      out.write("    <ul>\r\n");
      out.write("      <li><a href=\"benutzeranlegen.jsp\">Benutzer/Gruppe</a></li>\r\n");
      out.write("       <li><a href=\"mandatAnlegen.jsp\">Mandat</a></li>\r\n");
      out.write("       <li><a href=\"benutzerAnlegen.jsp\">Protokollieren</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	font-family: Arial, sans-serif;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	width: 800px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	backround: white;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 50%;\r\n");
      out.write("	left: 250px;\r\n");
      out.write("	transform: translateY(-50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group {\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("	display: block;\r\n");
      out.write("	margin-bottom: 9px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"], input[type=\"password\"], input[type=\"date\"] {\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-bottom: 2px solid #00BFFF;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	padding: 6px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".error {\r\n");
      out.write("	color: red;\r\n");
      out.write("	font-size: 0.9em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: flex-end;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("	padding: 15px 15px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	background-color: #00BFFF;\r\n");
      out.write("	color: black;\r\n");
      out.write("	border-radius: 3px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin: 0 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button button:hover {\r\n");
      out.write("	background-color: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".benutzer-btn {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	bottom: 10px;\r\n");
      out.write("	right: 10px;\r\n");
      out.write("}\r\n");
      out.write(".required {\r\n");
      out.write("    font-size: 1.5em;\r\n");
      out.write("    color: red;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h2>Benutzer/-gruppe</h2>\r\n");
      out.write("		<form action=\"benutzeranlegen\" method=\"post\">\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"vorname\">Benutzer-Vorname</label> \r\n");
      out.write("				<input type=\"text\" name=\"vorname\">\r\n");
      out.write("				<div class=\"error\" id=\"vornameError\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"nachname\">Benutzer-Nachname</label>\r\n");
      out.write("				<input type=\"text\"	name=\"nachname\">\r\n");
      out.write("				<div class=\"error\" id=\"nachnameError\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"username\">Username <span class=\"required\" title=\"Dieses Feld ist erforderlich!\">*</span></label> \r\n");
      out.write("				<input type=\"text\" name=\"username\">\r\n");
      out.write("				<div class=\"error\" id=\"usernameError\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"password\">Passwort <span class=\"required\" title=\"Dieses Feld ist erforderlich!\">*</span></label> \r\n");
      out.write("				<input type=\"password\" name=\"password\">\r\n");
      out.write("				<div class=\"error\" id=\"passwordError\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"password\">Passwort Wiederholen <span class=\"required\" title=\"Dieses Feld ist erforderlich!\">*</span></label> \r\n");
      out.write("				<input type=\"password\" name=\"passwordWiederholung\">\r\n");
      out.write("				<div class=\"error\" id=\"passwordWiederholungError\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"passwordValid\">Passwort Gültig Bis</label>\r\n");
      out.write("				<input type=\"date\" name=\"date\">\r\n");
      out.write("				<div class=\"error\" id=\"dateError\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"typ\">Benutzer-Typ</label> \r\n");
      out.write("				<input type=\"text\" name=\"benutzerTyp\">\r\n");
      out.write("				<div class=\"error\" id=\"benutzerTypError\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<button type=\"submit\">Anlegen</button>\r\n");
      out.write("			<button type=\"submit\">Abbrechen</button>\r\n");
      out.write("			<button type=\"button\" class=\"benutzer-btn\" onclick=\"window.location.href='benutzeranzeigen'\">Benutzer Anzeigen</button>\r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("		</form>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
